export const consts = {
  initialInputValue: 'init',
  searchKey: 'title',
  getPostsUrl: 'https://jsonplaceholder.typicode.com/posts',
  green: 'green',
  blue: 'blue',
  colorLabel: 'customColorName',
  textLabel: 'textValue',
  checkboxLabel: 'checkboxValue',
  greenTheme: 'set theme to green',
  blueTheme: 'set theme to blue',
  setInput: 'set theme to input value',
  toggleCheckbox: 'toggle checkbox',
  checkboxText: 'Test',
  submitText: 'form submit',
  resultsTitle: 'Results:',
  checkboxError: 'checkbox must be checked',
  minLengthError: 'minLength: 4',
  maxLengthError: 'maxLength: 8',
  latinLettersError: 'only latin letters',
  inputError: 'input must be:',
  noResults: 'No Results Found',
  userIdLabel: 'userId:',
  idLabel: 'id:',
  bodyLabel: 'body:',
  titleLabel: 'title:',
};
